# Generated by Django 5.2.5 on 2025-08-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_number', models.CharField(max_length=32, unique=True)),
                ('street_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('total_spots', models.IntegerField(blank=True, null=True)),
                ('available_spots', models.IntegerField(blank=True, null=True)),
                ('latest_update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
